# Generated by Django 6.0.3 on 2026-03-26 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iupac', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(choices=[('inorg', 'neorganska'), ('org', 'organska'), ('an', 'analitička'), ('phus', 'fizicka'), ('bch', 'biohemija')], max_length=50)),
                ('smiles', models.CharField(blank=True, max_length=50)),
                ('inchi', models.CharField(blank=True, max_length=50)),
                ('formula', models.CharField(max_length=50)),
                ('mweight', models.FloatField(blank=True, null=True)),
                ('cas_num', models.CharField(blank=True, max_length=50)),
                ('public', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('OXIDES', 'Oksidi'), ('INORG_ACIDS', 'Kiseline (Neorganske)'), ('BASES', 'Baze / Hidroksidi'), ('SALTS', 'Soli'), ('METALS', 'Metali i Legure'), ('NONMETALS', 'Nemetali'), ('COMPLEXES', 'Koordinaciona jedinjenja'), ('HYDROCARBONS', 'Ugljovodonici'), ('AROMATICS', 'Aromatična jedinjenja'), ('ALCOHOLS', 'Alkoholi i Fenoli'), ('CARBOXYLIC', 'Karboksilne kiseline'), ('CARBONYLS', 'Aldehidi i Ketoni'), ('ESTERS', 'Estri i Etri'), ('AMINES', 'Amini i Amidi'), ('ORGANOMETALLIC', 'Organometalna jedinjenja'), ('POLYMERS', 'Sintetički polimeri'), ('PROTEINS', 'Proteini / Peptidi'), ('CARBOHYDRATES', 'Ugljeni hidrati'), ('LIPIDS', 'Lipidi'), ('NUCLEIC', 'Nukleinske kiseline'), ('SOLVENTS', 'Rastvarači'), ('CATALYSTS', 'Katalizatori'), ('MIXTURES', 'Smeše / Formulacije'), ('REAGENTS', 'Reagensi')], max_length=50, null=True)),
                ('logp', models.FloatField(blank=True, null=True)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('h_donors', models.IntegerField(blank=True, null=True)),
                ('h_acc', models.IntegerField(blank=True, null=True)),
                ('pdb', models.FileField(blank=True, null=True, upload_to='pdb/')),
                ('structure', models.BooleanField(default=False)),
                ('calcproperties', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.compound')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('tt', 'tacka topljenja (°C)'), ('tk', 'tacka kljucanja (°C)'), ('r', 'rastvorljivost (g/L)'), ('gst', 'gustina (g/cm3)'), ('logp', 'logP'), ('pk', 'pKa')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.compound')),
            ],
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spectrumtype', models.CharField(choices=[('ir', 'ir'), ('nmr', 'nmr'), ('ms', 'ms')], max_length=50)),
                ('info', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='spectra/')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra', to='core.compound')),
            ],
        ),
    ]
