# Generated by Django 6.0.3 on 2026-03-26 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cas_number', models.CharField(blank=True, max_length=50)),
                ('formula', models.CharField(blank=True, max_length=50)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('un_number', models.CharField(blank=True, max_length=50)),
                ('hazard_symbol', models.CharField(blank=True, choices=[('GHS1', 'Eksplozivno'), ('GHS2', 'Zapaljivo'), ('GHS3', 'Oksidativno'), ('GHS4', 'Gas pod pritiskom'), ('GHS5', 'Koroyivno'), ('GHS6', 'Toksicno'), ('GHS7', 'Stetno'), ('GHS8', 'Opasno po zdravlje'), ('GHS9', 'Opasno po ziv. sredinu')], max_length=50)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_chemicals', to='core.compound')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('catalog_number', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(choices=[('mg', 'miligram'), ('g', 'gram'), ('kg', 'kilogram'), ('mL', 'mililitar'), ('L', 'litar'), ('mmol', 'milimol'), ('mol', 'mol')], max_length=50)),
                ('quantity', models.FloatField()),
                ('purity', models.FloatField(blank=True, null=True)),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('msds', models.FileField(blank=True, null=True, upload_to='inventory/msds/')),
                ('coa', models.FileField(blank=True, null=True, upload_to='inventory/coa/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.chemical')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_notes', to='inventory.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
